#######################################
# Instructions:
# 1. # is for comments
# 2. Indentation must be strictly aligned using spaces
# 3. Please use English characters
#######################################

# Application base configuration
app:
  name: douyin-downloader
  version: 1.0.0
  debug: false

# Download configuration
download:
  max_concurrent: 3
  chunk_size: 8192
  retry_times: 3
  timeout: 30

# Logging configuration
logging:
  level: INFO
  file_path: logs/
  max_size: 10485760 # 10MB
  backup_count: 5

# API configuration
api:
  base_url: https://api.example.com
  timeout: 10
  retry_count: 3

# Download links, supports multiple links
link:
  - 'https://v.douyin.com/xxxxx/'
  - 'https://v.douyin.com/yyyyy/'

# Download save location, defaults to current directory
path: './downloads'

# Download options
music: true # Whether to download music
cover: true # Whether to download covers
avatar: true # Whether to download avatars
json: true # Whether to save JSON data
folderstyle: true # Whether to use folder style saving

# Download mode settings
mode:
  - 'post' # post:posted works like:liked works mix:collection works

# Download quantity settings (0 means download all)
number:
  post: 0 # Number of posted works to download
  like: 0 # Number of liked works to download
  allmix: 0 # Number of all collections to download
  mix: 0 # Number of works per collection to download
  music: 0 # Number of music works to download

# Other settings
thread: 5 # Number of download threads
database: true # Whether to use database

# Incremental update configuration
increase:
  post: false # Whether to incrementally download homepage works
  like: false # Whether to incrementally download liked works
  allmix: false # Whether to incrementally download homepage collections
  mix: false # Whether to incrementally download single collection
  music: false # Whether to incrementally download music works

# Cookie configuration (choose one)
cookies: # Key-value pair format
  msToken: xxxxxx
  ttwid: xxxxxx
  odin_tt: xxxxxx

#cookie: "msToken=xxxxxx; ttwid=xxxxxx;"  # String format

# Time range filter (optional)
start_time: '2023-01-01' # Start time, format: YYYY-MM-DD
end_time: 'now' # End time, use "now" for current time
